package com.yunche.loan.domain.vo;

import lombok.Data;

@Data
public class UniversalCustomerDetailVO {

    private String customer_id;
    private String customer_name;
    private String customer_nation;
    private String customer_birth;
    private String customer_identity_validity;
    private String customer_lend_card;
    private String customer_id_card;
    private String customer_mobile;
    private String customer_age;
    private String customer_sex;
    private String customer_apply_date;
    private String customer_address;
    private String customer_marry;
    private String customer_identity_address;
    private String customer_mobile_area;
    private String customer_education;
    private String customer_company_name;
    private String customer_company_phone;
    private String customer_company_address;
    private String customer_month_income;
    private String customer_house_type;
    private String customer_house_owner;
    private String customer_house_feature;
    private String customer_house_address;
    private String customer_info;
    private String customer_cust_type;
    private String customer_principal_cust_id;
    private String customer_cust_relation;
    private String customer_gmt_create;
    private String customer_gmt_modify;
    private String customer_postcode;
    private String customer_working_years;
    private String customer_duty;
    private String customer_household_nature;
    private String customer_children_num;
    private String customer_reserve_mobile;
    private String customer_company_nature;
    private String customer_industry_category;
    private String customer_income_certificate_company_name;
    private String customer_income_certificate_company_address;
    private String customer_family_address;
    private String customer_family_mobile;
    private String customer_family_monthly_income;
    private String customer_feeding_num;
    private String customer_floor_space;
    private String customer_house_owner_relation;
    private String customer_bank_card_transmit_address;
    private String customer_bank_card_transmit_postcode;
    private String customer_house_certificate_type;
    private String customer_bank_card_transmit_address_type;
    private String customer_company_postcode;
    private String customer_elementary_school;
    private String customer_professional;
    private String customer_family_person_num;
    private String customer_debt_ratio;
    private String bank_info;
    private String bank_result;
    private String process_bank_credit_result;
    private String process_bank_credit_info;
    private String process_bank_add_condition;
    private String society_info;
    private String society_result;
    private String process_society_credit_result;
    private String process_society_credit_info;
    private String process_society_add_condition;
}
